package com.agileactors.domain;

public enum AuditLogType {
    CUSTOMER_INIT, CUSTOMER_DELETE, CUSTOMER_UPDATE, CONTRACT_INIT, CONTRACT_DELETE, CONTRACT_UPDATE, USER_INIT, USER_DELETE, USER_UPDATE
}
