version: '2.3'

services:
  training-app-auditlog-service:
    image: "training-app-auditlog-service:1.0"
    cpu_shares: 2
    depends_on:
      training-app-auditlog-service-db:
        condition: service_healthy
      training-app-auditlog-kafka-service:
        condition: service_healthy
    environment:
      DB_HOST: training-app-auditlog-service-db
      DB_PORT: 5432
      JAVA_OPTS: "-Duser.timezone=Europe/Athens"
      SERVER_PORT: 8080
      MANAGEMENT_SERVER_PORT: 8180
    ports:
      - "8280:8080"
      - "8281:8081"

  training-app-auditlog-service-db:
    image: postgres:16-alpine
    command: "postgres"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "auditlog"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8432:5432"

  training-app-auditlog-kafka-service:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    healthcheck:
      test: [ "CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1" ]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s
    ports:
      - 9081:8081
      - 9082:8082
      - 9092:9092
      - 9644:9644
